language: python
sudo: true

python:
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.10"

install:
    - pip install -e .[tests]

script:
    - pytest -v --cov=atoma tests/
    - pycodestyle --ignore=E252 atoma tests

after_success:
  - coveralls

notifications:
    email: false
