name: Test

on: [push, pull_request, workflow_dispatch]

env:
  FORCE_COLOR: 1

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          # Include new variables for Codecov
          - { codecov-flag: GHA_Windows, os: windows-latest }
          - { codecov-flag: GHA_macOS, os: macos-latest }
          - { codecov-flag: GHA_Ubuntu, os: ubuntu-latest }

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: "setup.py"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U wheel
          python -m pip install -e ".[tests]"

      - name: Run tests
        run: |
          pytest -v --cov=atoma tests/ --cov-report xml
          pycodestyle --ignore=E252 atoma tests

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          flags: ${{ matrix.codecov-flag }}
          name: ${{ matrix.os }} Python ${{ matrix.python-version }}
